export const wines = [
  {
    id: 1,
    imageUrl: '/assets/red-wine.jpg',
    isNew: true,
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 2,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 3,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isNew: true,
    isFinished: true,
  },
  {
    id: 4,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 5,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isNew: true,
    isFinished: true,
  },
  {
    id: 6,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 7,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 8,
    imageUrl: '/assets/red-wine.jpg',
    label: 'Wine',
    isFinished: true,
  },
  {
    id: 1,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 2,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 3,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 4,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 5,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 6,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 7,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
  {
    id: 8,
    imageUrl: '/assets/red-wine.jpg',
    progress: 22,
    label: 'Wine',
  },
];
